version: "3.4"

services:
  backend:
    build: ./backend
    container_name: backend_node
    volumes:
      - ./backend:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - 8080:8080
    command: npm run start

  database:
    container_name: database_pgsql
    env_file:
      - ./.env
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - 5432:5432
    volumes:
      - /home/tmp/pgsql:/var/lib/postgresql/data