version: "3.4"

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules
    ports:
      - 8080:8080

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    ports:
      - 9000:9000

  database:
    container_name: database_pgsql
    env_file:
      - ./.env
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - 5432:5432
    volumes:
      - /home/tmp/pgsql:/var/lib/postgresql/data